### ISSUE TITLE
ACProgressCustom custom speed crashing

### ISSUE THREAD

**Issue by adarsh10** [Cloudist/ACProgressLite#6]
This is my code: 

public void onClick(View v) {
                ACProgressCustom dialog = new ACProgressCustom.Builder(JoinNow.this)
                        .useImages(R.drawable.p0, R.drawable.p1, R.drawable.p2, R.drawable.p3)
                        .speed(3000)
                        .build();
                dialog.setCanceledOnTouchOutside(true);
                dialog.show();
            }

The application crashes and the logs are: 

Process: in.trujobs.truapp, PID: 18636
java.lang.IllegalArgumentException
at java.util.Timer.scheduleAtFixedRate(Timer.java:526)
at cc.cloudist.acplibrary.ACProgressCustom.show(ACProgressCustom.java:76)
at in.trujobs.truapp.JoinNow$1.onClick(JoinNow.java:27)
at android.view.View.performClick(View.java:4444)
at android.view.View$PerformClick.run(View.java:18440)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5052)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
at dalvik.system.NativeStart.main(Native Method)

How to set my custom speed of 3 seconds?

**Comment by prasanthmurugan** [comment]
I am facing the same issue !!! did you found  the solution??
