### ISSUE TITLE
ACProgressCustom.java:79 needs a try catch...

### ISSUE THREAD

**Issue by renevdkooi** [Cloudist/ACProgressLite#8]
stacktracejava.lang.ArithmeticException: divide by zero
at cc.cloudist.acplibrary.ACProgressCustom$2.run(ACProgressCustom.java:79)
at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by vinojvetha** [comment]
NullpointerException
com.santander.us.base.utils.ACProgressCustom$2.run
 at java.util.Timer$TimerImpl.run(Timer.java:284)

Do you have any idea about that?
